[project]
name = "drf-p37"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.4",
    "django-ckeditor-5>=0.2.20",
    "django-filter>=25.2",
    "djangorestframework>=3.17.1",
    "djangorestframework-camel-case>=1.4.2",
    "djangorestframework-simplejwt>=5.5.1",
    "djangorestframework-xml>=2.0.0",
    "djangorestframework-yaml>=2.0.0",
    "drf-spectacular>=0.29.0",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.2",
]

