# Generated by Django 6.0.4 on 2026-04-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
