# Generated by Django 6.0.4 on 2026-04-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0004_post_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("password", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("registered_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
