# Generated by Django 6.0.4 on 2026-04-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0005_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.CharField(default="Student", max_length=25),
        ),
    ]
